### ISSUE TITLE
Major Bug- Round Ending events on Healer Storyteller with only two active crewmembers.

### ISSUE THREAD

**Issue by Hawk-v3** [Occulus-Server/Occulus-Eris#131]
#### Description of issue

![image](https://user-images.githubusercontent.com/1232355/104103779-d1e84200-529b-11eb-86c5-e72dba5373cf.png)

[Common] NEV Northern Light System Announcer states, "Biohazard Alert: Confirmed outbreak of level 7 biohazard aboard CEV Northern Light. All personnel must contain the outbreak."

#### Difference between expected and actual behavior

It's healer. This isn't meant to happen.

#### Steps to reproduce 

Don't know.

#### Length of time in which bug has been known to occur

Happened today.

#### Client version, Server revision & Game ID

Server revision: master - 2021-01-09
ebe09579a9d6ee4664a75535ca62b6b4b0fa9d4e

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by ShadzFen** [comment]
PR #134 fixed this issue.
