### ISSUE TITLE
Alt titles do not get paid

### ISSUE THREAD

**Issue by cebutris** [Occulus-Server/Occulus-Eris#160]
#### Description of issue

Job alt-titles do not get paid wages as they should

#### Difference between expected and actual behavior

Alt-titles should get paid. They do not

#### Steps to reproduce 
Be an alt title. Wait for wages to roll through. See you do not get paid.

#### Specific information for locating
wage code

#### Length of time in which bug has been known to occur
For as long as we've had alt titles

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
I'm trying to poke at this issue now. It does look like the alt title jobs do have proper wages listed (since the code that handles how much they get paid also determines their starting cash) but something is goofy in the actual payout code (in economy.dm, specifically the pay_wages() code)
