### ISSUE TITLE
mining Exosuits are useless due to mining exo suit drill bits breaking

### ISSUE THREAD

**Issue by RadiantFlash7** [Occulus-Server/Occulus-Eris#171]
#### Description of issue
Exosuit drill bits are useless and break in one use.

#### Difference between expected and actual behavior
Steel bits, Even plasteel bits. All break on first use. Makes mining exosuits /completely/ useless.

#### Steps to reproduce 
mine with an exosuit, watch as your drill bit breaks on first use. Even expensive fancy drillbits. Cry inside.

#### Specific information for locating

The plasteel drill head breaks apart!

#### Length of time in which bug has been known to occur

As long as I've been on occulus

#### Client version, Server revision & Game ID

Server revision: master - 2021-01-24

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)
*Edit: Fixed the boxes for you.

**Comment by zackerycodestoo** [comment]
Issue appears to originate from lines 205-207 in utility.dm:

```
 /obj/item/weapon/material/drill_head/Initialize()
    . = ..()
    durability = 2 * (material ? material.integrity : 1)
```

in this block of code, 'material' is trying to pull a null value. Inspecting the variables of the drill head after spawn shows that it does have a material properly assigned to it, but the durability assignment is failing in this piece of code because material is null when it tries to run
