### ISSUE TITLE
Mining smelter does not process making plasteel correctly.

### ISSUE THREAD

**Issue by SectoidDan** [Occulus-Server/Occulus-Eris#176]
#### Description of issue
Plasteel is an alloy of hematite (iron), carbon (coal), and phoron. Steel is an alloy of iron and carbon. When the smelter is set to smelt iron, carbon, and phoron, it produces both plasteel and steel sheets at the same time.

#### Difference between expected and actual behavior
Ultimately, the smelter should be configurable to output only plasteel and nothing else.
When the smelter is set to smelt iron, carbon, and phoron all together, it should produce only plasteel and no steel. Alternatively, the recipe for plasteel should be changed to not overlap with steel, perhaps by simply removing carbon from the alloy recipe. 

Note also that plasteel already has a 0.3 production modifier from alloys.dm - this bug compounds the difficulty of producing plasteel for miners and cargo in general beyond the intended level.

#### Steps to reproduce 
1. Put hematite, carbon, and phoron ore in a smelter. 
2. Set it to smelt all three. 
3. Watch and cry as most of the ores get turned into useless cheap steel instead of glorious strong (and most importantly) valuable plasteel.

#### Specific information for locating

code/modules/mining/alloys.dm and code/game/machinery/smelter.dm are probably the relevant files.

#### Length of time in which bug has been known to occur

Since I started playing here at least.

#### Client version, Server revision & Game ID

master - 2021-01-24

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [✔] Issue could be reproduced at least once (all the time)
- [✔] Issue could be reproduced by different players (I asked Rynn but it happens literally every time anyway)
- [✔] Issue could be reproduced in multiple rounds (every round)
- [✔] Issue happened in a recent (less than 7 days ago) round (yes)
- [✔] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
Some inspection of the code seems to reveal that this is working as intended in the way that it tries to smelt plasteel first and then only smelts steel if it runs out of ingredients. However, I do agree that it would be much, much better if you could choose exactly what gets alloyed if you aren't interested in smelting steel by itself.

I'm too unfamiliar with hrefs and pulling data out of datums right now to tackle this myself at this time -- if any other dev is interested, the file that needs to be changed is code/modules/mining/machine_processing.dm. The idea that I had to tackle this was to let the console have an href addition to toggle yes/no on different alloy types (the console href definition begins at line 61) and have the processing unit pull from that same list. I don't expect the processing unit needs to be changed aside from modifying the list of valid alloys (the variable _alloy_data_)

**Comment by Jamini** [comment]
It certainly isn't working that way Mr.Fox . Right now tit appears to run through each possible alloy and smelt them if possible, regardless if it's alloying anything else.

I can fix this, but it will slow down the rate of alloying and prohibit doing multiple alloys at once. (So if you have plasteel and borosilicate set, it will do plasteel until it's out, then do boro.)
