### ISSUE TITLE
Mech drill replacement bits have incorrect durability

### ISSUE THREAD

**Issue by zackerycodestoo** [Occulus-Server/Occulus-Eris#188]
#### Description of issue

Crafted drill bits are not spawning with the correct durability. I am uncertain why this is happening since I confirmed they had the correct durability during my testing. This issue is primarily a reminder for myself to look at the code again in the morning.

Drill heads produced from mech drills work with the proper durability as expected.

#### Difference between expected and actual behavior

Steel drill heads should spawn with 200 durability, but they spawn with 0.

#### Steps to reproduce 

1. Craft a steel drill head from the crafting menu
2. Durability is 0

#### Specific information for locating

Utility.dm starting at 198. ApplyDurability() proc is seemingly not working as expected (proc defined at line 223)

#### Length of time in which bug has been known to occur

Presumably ever since new drill durability fix was implemented on Wednesday Jan 27

#### Client version, Server revision & Game ID

![image](https://user-images.githubusercontent.com/77511162/106232013-037c6b00-61c1-11eb-9945-4c6e40a07384.png)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by RadiantFlash7** [comment]
I came across this while mining with exo. Not sure if all types, or just steel. But the original bit in the drill worked perfectly. All the replacement bits durabilities was broke.
