### ISSUE TITLE
Guns cycle expended rounds

### ISSUE THREAD

**Issue by JMoldy** [Occulus-Server/Occulus-Eris#195]
#### Description of issue
FIrearms that automatically eject casings will eject spent casings loaded into the chamber when fired as if the gun cycled properly.

#### Difference between expected and actual behavior
Expected: Load empty casings into magazine. Load magazine into gun. Turn off safety. Attempt to fire gun. Gun should go click, empty casing should remain in the chamber.

Actual: Load empty casings into magazine. Load magazine into gun. Turn off safety. Attempt to fire gun. Gun goes click, empty casing falls to the floor.

#### Steps to reproduce 
Same as above

#### Specific information for locating
Under the file /code/modules/projectiles/guns/projectile.dm
Lines 80 - 121
```
/obj/item/weapon/gun/projectile/proc/process_chambered()
	if (!chambered) return

	if(chambered.is_caseless)
		QDEL_NULL(chambered)
		return
	// Aurora forensics port, gunpowder residue.
	if(chambered.leaves_residue)
		var/mob/living/carbon/human/H = loc
		if(istype(H))
			if(!H.gloves)
				H.gunshot_residue = chambered.caliber
			else
				var/obj/item/clothing/G = H.gloves
				G.gunshot_residue = chambered.caliber

	switch(handle_casings)
		if(EJECT_CASINGS) //eject casing onto ground.
			chambered.forceMove(get_turf(src))
			for(var/obj/item/ammo_casing/temp_casing in chambered.loc)
				if(temp_casing == chambered)
					continue
				if((temp_casing.desc == chambered.desc) && !temp_casing.BB)
					var/temp_amount = temp_casing.amount + chambered.amount
					if(temp_amount > chambered.maxamount)
						temp_casing.amount -= (chambered.maxamount - chambered.amount)
						chambered.amount = chambered.maxamount
						temp_casing.update_icon()
					else
						chambered.amount = temp_amount
						QDEL_NULL(temp_casing)
					chambered.update_icon()

			playsound(src.loc, casing_sound, 50, 1)
		if(CYCLE_CASINGS) //cycle the casing back to the end.
			if(ammo_magazine)
				ammo_magazine.stored_ammo += chambered
			else
				loaded += chambered

	if(handle_casings != HOLD_CASINGS)
		chambered = null 
```

This doesn't check if the chambered round actually fired or is capable of firing. This affects all autoejecting guns.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Hawk-v3** [comment]
I don't think this is a bug. It is incorrect to *reality*, yes, but I would consider this a Quality of Life thing as the character just working out the dud round.
