### ISSUE TITLE
Gun examine UI is blank

### ISSUE THREAD

**Issue by zackerycodestoo** [Occulus-Server/Occulus-Eris#205]
#### Description of issue

When you examine a gun (old and new guns), the UI that appears is blank. This was first reported in Discord by ZenithEevee and confirmed by myself and another player.

#### Difference between expected and actual behavior

![image](https://user-images.githubusercontent.com/77511162/106800504-8ae93480-662e-11eb-9d14-3ac964be92d8.png)

This blank UI was showing up for multiple players, even after clearing cache and reconnecting. It should be showing information about the gun stats.

#### Steps to reproduce 

1. Examine a gun on the live server

#### Length of time in which bug has been known to occur

This is _possibly_ connected to recent code changes to do with oldifying guns.

#### Client version, Server revision & Game ID

![image](https://user-images.githubusercontent.com/77511162/106800693-cbe14900-662e-11eb-90f7-0c7535f5e1ea.png)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
There was a file that got unincluded on the server. Everything is working now.

My bad.
