### ISSUE TITLE
Colbalt Op lockers only have a Martin

### ISSUE THREAD

**Issue by Ikmachek** [Occulus-Server/Occulus-Eris#216]
#### Description of issue
Cobalt Aegis Op lockers have a Martin, nothing else

#### Difference between expected and actual behavior
WHERE'S MY FUCKING SOL, OR ANYTHING ELSE

#### Steps to reproduce 
Join as Aegis, open a op locker, realize your budget has been cut by 500% and you get a single gun with no battery

#### Specific information for locating
I'd start looking at the map file for lockers

**Comment by Michiyamenotehifunana** [comment]
Caused by https://github.com/Occulus-Server/Occulus-Eris/pull/211

**Comment by Michiyamenotehifunana** [comment]
Line 42 of `zzzz_modular_occulus/code/game/jobs/job/security.dm`

`/obj/structure/closet/secure_closet/personal/security/populate_contents()
	new /obj/item/weapon/gun/energy/gun/martin(src)`

Jams thought procs don't get overwritten so jams excluded the `..()`

**Comment by Jamini** [comment]
Hotfix #217 is up

**Comment by Ikmachek** [comment]
This god fixed, however there's no 200s cell in the locker, who cares though because there's 50 in the public armory.
