### ISSUE TITLE
Excelsior machinegun can't be fired wielded

### ISSUE THREAD

**Issue by RadiantFlash7** [Occulus-Server/Occulus-Eris#222]
#### Description of issue
Excelsior Machinegun doesn't heckin work when wielded. 
![excelsiorbug](https://user-images.githubusercontent.com/12434413/107176753-41864580-699e-11eb-90dd-73c297a67b35.png)

#### Difference between expected and actual behavior
Tells you to wield machinegun to fire better,
When wielding machine, it tells you the offhand is occupied and it can't be used!

#### Steps to reproduce 
Try firing excelsior machine gun two handed!

#### Specific information for locating

Excelsior machine gun 
You can't fire Wielded Excelsior machine gun with Wielded Excelsior machine gun - offhand in the other hand.

#### Length of time in which bug has been known to occur

No idea! I've never used excel weapoms before!

#### Client version, Server revision & Game ID

master - 2021-02-07
7701e34a1bfdef80bcc5e8c47adb7b9a7cbaadeb

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Michiyamenotehifunana** [comment]
The item in question was an old debug item from the early days of Eris, and has been blacklisted upstream.

Refer to: https://github.com/discordia-space/CEV-Eris/pull/5758

**Comment by JMoldy** [comment]
the excel machine gun was blacklisted a while ago because it is very buggy and should not be spawning at all.
