### ISSUE TITLE
Projectiles overpen to a stupid degree

### ISSUE THREAD

**Issue by Ikmachek** [Occulus-Server/Occulus-Eris#233]
#### Description of issue
Almost every bullet now since the scrap ammo update will act like a lethal rifle round when shooting roaches and not only kill the roach by fly off past it.

#### Difference between expected and actual behavior
I don't expect shooting a .35 rubber out of a .8 pen gun at the ground to fly off and blast out windows or other people

#### Steps to reproduce
As above, just shoot any roach with any pistol and any round type and watch the bullets continue past the roach, when before they terminated at the roach.

#### Length of time in which bug has been known to occur
Since the scrap ammo PR

**Comment by zackerycodestoo** [comment]
May be the result of porting https://github.com/discordia-space/CEV-Eris/pull/5881 in #193
