### ISSUE TITLE
Cargo's Random Wave radio no longer gives out loot paper.

### ISSUE THREAD

**Issue by RadiantFlash7** [Occulus-Server/Occulus-Eris#243]
#### Description of issue
Cargo's Random Wave radio no longer gives out loot paper.

#### Difference between expected and actual behavior

Should supply loot paper every 40 minutes. at max, if not sooner.

#### Steps to reproduce 
Stare at lack of loot treasure hunting in cargo over the round.

#### Specific information for locating

/obj/item/device/radio/random_radio
code\game\objects\items\devices\radio\radio.dm

#### Length of time in which bug has been known to occur
Since the loot update.

#### Client version, Server revision & Game ID

Server revision: master - 2021-02-09
4e1a83ac9e1da1fa4980a5cb11cfd95c1c64936f

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ X] Issue could be reproduced at least once
- [X ] Issue could be reproduced by different players
- [ X] Issue could be reproduced in multiple rounds
- [X ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
Random wave radio calls /proc/pick_n_take_stash_datum() -- it is always returning a null stash. Tori suspects possible a new code is being used to generate stashes and the Random wave needs updated.

**Comment by Jamini** [comment]
I'm not so sure. I'm wondering if we might just be running out of stashes (there is a hard limit) on regular maintgen? A lot of those papers are scattered around.
