### ISSUE TITLE
Blattedin reviving is all kinds of broken

### ISSUE THREAD

**Issue by cebutris** [Occulus-Server/Occulus-Eris#249]
#### Description of issue
Blattedin is reviving roaches when it's in their system. It's also reviving fuhrers.

#### Difference between expected and actual behavior
Blattedin should only be reviving roaches on touch, such as a spraybottle or gas cloud (given the revive proc is on_touch)

Fuhrers should not be getting revived, they start with `bug.blattedin_revives_left = 0`

#### Steps to reproduce 

give blattedin to a dead roach

**Comment by Shadow-Quill** [comment]
Apparently fixed by 316, but the magic words weren't in the PR description.

**Comment by zackerycodestoo** [comment]
Potentially fixed -- I did testing after 316 but it was inconclusive. Can be re-opened if it proves to still be bugged
