### ISSUE TITLE
Sergal bases don't metabolize certain chemicals.

### ISSUE THREAD

**Issue by Torque4607** [Occulus-Server/Occulus-Eris#257]
#### Description of issue

Sergal-base genemods (and normal sergals) don't process some chemicals. Known affected: spaceacillin, paracetemol, tramadol. These and possibly a few others remain in the blood stream where they act but never metabolize out.

#### Difference between expected and actual behavior

Expected behavior is for the chemicals to leave the bloodstream as determined by the metabolism rate.

#### Steps to reproduce 

-Join game using sergal base.
-Inject one of the three chemicals above (possibly others).
-Keep scanning yourself over a few minutes, notice the lack of metabolism.

#### Specific information for locating

Known affected chemicals: Tramadol, paracetamol, spaceacillin

#### Length of time in which bug has been known to occur

At least since Syzygy.

#### Client version, Server revision & Game ID

36b14ddceb830728f838ac0ed3620964f74434c4

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
Appears fixed per #284 with the exception of paracetamol
