### ISSUE TITLE
Perks appear double on oddity examination

### ISSUE THREAD

**Issue by Zenitheevee** [Occulus-Server/Occulus-Eris#273]
#### Description of issue

Perks on Oddities repeat twice.

#### Difference between expected and actual behavior

Expected:
Examine oddity
https://i.imgur.com/OuZVgHa.png

Actual:
Examine Oddity
https://i.imgur.com/OuZVgHa.png

#### Steps to reproduce 

Get any oddity
Examine oddity

#### Specific information for locating

Has only been an issue as of the latest update (Friday, Feb. 19th)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
Fixed in #272
