### ISSUE TITLE
Health scanners (portable and full) should show blood oxygenation/pressure levels

### ISSUE THREAD

**Issue by zackerycodestoo** [Occulus-Server/Occulus-Eris#281]
#### Description of issue

Per Discord, the health scanner should show blood oxygenation/pressure levels. Currently the only way to get this information is to look at suit sensors. 

#### Difference between expected and actual behavior

The body scanner does not show any information. The portable scanner only shows 'oxygen level normal' without more description, but no blood pressure.

#### Steps to reproduce 

Compare a portable health scanner to looking at someone with vitals tracker active on their uniform

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
Blood oxygenation is only a function of getOxyLoss that is obfuscated. The health scanner and body scanner directly shows oxyloss as far as I can tell

**Comment by Jamini** [comment]
Both of these are displayed, just not in the same way as health scanners (I.E. blood levels and oxyloss values). There isn't much really to duplicate this information.
