### ISSUE TITLE
Putting a Propaganda Chip in Science's Deconstructive Analyzer breaks the R&D console

### ISSUE THREAD

**Issue by DARG0N** [Occulus-Server/Occulus-Eris#297]
#### Description of issue
See: Subject line

#### Difference between expected and actual behavior
What should happen: Research Console continues working.
What did happen: Research console broke entirely; the interface refused to pop up when interacting with the console, even after entirely disassembling and reassembling the research console. Admin intervention ended up being necessary.

#### Steps to reproduce 
-Find Propaganda chip
-Put it in Deconstructive Analyzer

#### Specific information for locating

-Deconstructive Analyzer
-Core R&D Console
-Propaganda Chip
#### Length of time in which bug has been known to occur
-Highpop, 27 Feb 2021

#### Client version, Server revision & Game ID

Server revision: master - 2021-02-26
533cc12adc2f6c9af3b16ff345946e07b96378db

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
Initial suspect seems to be that the propaganda chip (also the spy sensor) are tagged with an invalid tech origin, TECH_MAGNETS -- proper origin is TECH_MAGNET
