### ISSUE TITLE
Carrion spiders cannot be removed.

### ISSUE THREAD

**Issue by Torque4607** [Occulus-Server/Occulus-Eris#298]
#### Description of issue

Spiders that show up as "unknown bodies" on the scanner _cannot_ be removed without needing a resleeve.

#### Difference between expected and actual behavior

Expected behavior: removing a carrion spider such as observing spider or flashbang spider will let it be pulled out of the body the same as shrapnel extraction surgery.
Actual behavior: It just kinda shows up on the deck for a moment, then pops back into the body.

#### Steps to reproduce 

Get a spider into someone as a carrion.
Attempt to remove said spider.
Watch as it teleports back into the body.

#### Length of time in which bug has been known to occur

Uncertain, at least since 28.02.2021.

#### Client version, Server revision & Game ID

533cc12adc2f6c9af3b16ff345946e07b96378db

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players (In the same round, occurred on at least three different characters).
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
As an update... they can be killed if you're REALLY fast, I found. You have only a split second to crush the spider before it jumps back into the body.

**Comment by Jamini** [comment]
Looks like a flag isn't getting reset when spiders are ordered to attach to nearby people. Should be a pretty easy fix!
