### ISSUE TITLE
Brain cannot be re-inserted into FBPs and are deleted if their MMI is removed

### ISSUE THREAD

**Issue by zackerycodestoo** [Occulus-Server/Occulus-Eris#299]
#### Description of issue

An FBP with its brain removed can't be put back in a body, causing a whole slew of issues. Additionally, MMIs or posibrains inserted into the body will be deleted if they are removed again. There is no way to bring the FBP player back into the round without a total soulcrypt resleeve.

#### Difference between expected and actual behavior

It's expected to have a 'connect' button to give the posibrain/MMI control over the body again. The brain connection code needs to be looked at and then given to MMIs/posibrains.

#### Steps to reproduce 

1. Remove brain from an FBP
2. Place brain in an MMI
3. Insert MMI into head
4. FBP player is not in control of their body. Try to remove MMI, MMI is deleted. This also happens to posibrains.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
Indirectly related code at `code/modules/surgery/surgery.dm` line 207 -- bugs with failure to connect limbs to a non-buckled prosthetic must be fixed first (since a non-mob prosthetic torso cannot be operated on -- this is indirectly linked to this issue but not a direct cause of the problem)

**Comment by Jamini** [comment]
This is fixed in #454

We now have synthetic brains. Click a soulcrypt, brain in a mmi, or positronic brain on a synthetic brain to upload it, and apply the synthetic brain to the FBP
