### ISSUE TITLE
Carrion "Spider Menu" Stops popping up after unknown event

### ISSUE THREAD

**Issue by Zenitheevee** [Occulus-Server/Occulus-Eris#301]
#### Description of issue

After spawning what some may say is "Way too many spiders" and doing a lot of things involving butchering kampfer and jaeger roaches, The spider menu stopped popping up entirely.

#### Difference between expected and actual behavior

Expected behavior: Spider menu works, maybe lags out a bit.

Actual behavior: *Insert dialup noises* 

#### Steps to reproduce 

Step 1: Become carrion
Step 2: Spawn a whole lodda spiders 
Step 3: Do a lot of random shit. 
Step 4: Realize your children will no longer help you

#### Specific information for locating

A recent test is putting doubt in me that its a spiderling limit, and maybe instead something along the lines of runtimes or verb issues.
While i'm not sure if it helps, I've only used Flashbang, Mindboil and Observer spiderlings. 

#### Length of time in which bug has been known to occur

N/A, Though it is possible it could been an issue since inception 

#### Client version, Server revision & Game ID

Game ID.. uh, Saturday highpop ~6-ish pm PST, 
Client version is.. i think its 153X? Its one of the fairly stable ones before compiling inexplicably stopped working.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
At some point I think we managed to resolve this one. If anyone has this issue reoccur please reopen.
