### ISSUE TITLE
Lever-action shotguns can no longer be cut down.

### ISSUE THREAD

**Issue by SectoidDan** [Occulus-Server/Occulus-Eris#306]
#### Description of issue
As title - clicking on a lever-action shotgun no longer cuts down the shotgun, and instead does nothing (but does drain some battery power from circular saws when attempted, interestingly).
NB: cutting down the double-barrel shotgun still works perfectly fine. I have not been able to properly test cutting down a lever-action rifle but I suspect the same issue would occur.

#### Difference between expected and actual behavior
Clicking on a lever-action shotgun with a cutting tool should cut down the shotgun, like the double-barrel. 

#### Steps to reproduce 

1. Get a lever-action shotgun from a miner's locker
2. Get a tool with the cutting quality, such as a handsaw or circular saw.
3. While holding the cutting tool, click the shotgun, either with it in hand or on a table or the ground.
4. Cry.

#### Specific information for locating

Since the double-barrel shotgun gets cut down fine, and it has the ancient legacy hard-coded method of cutting down, it's probably an issue with the lever-actions and their "sawn_result" vars. Or something, I'm not a coder.

#### Length of time in which bug has been known to occur

Approximately since the introduction of lever-action _rifles_, though I can't be sure about that and it's mostly just a feeling. I was absent for a while when the lever rifles were first added.

#### Client version, Server revision & Game ID

Latest versions.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
This has been resolved.
