### ISSUE TITLE
Cryo consoles will tease you about guns they won't actually let you have.

### ISSUE THREAD

**Issue by SectoidDan** [Occulus-Server/Occulus-Eris#307]
#### Description of issue
When someone enters a cryogenics tube and is despawned, the console saves whatever is in their suit slot as well as their suit storage slot, and allows people to retrieve those stored items.

However, while items in the suit storage slot (usually guns but tested with an oxygen tank) will be listed in the stored items, and can be selected for retrieval, and even though the console will happily claim it has dispensed them, it doesn't actually drop anything when you try it. 

Note that I'm talking specifically about the suit storage _slot_, not internal storage on clothing that goes in the suit slot. Those work perfectly fine, preserving their contents. 

#### Difference between expected and actual behavior
If Ellis goes to cryo wearing an armour vest with a Sol slung on it, I should be able to get a free Sol from the cryo console, damnit.
ALTERNATIVELY it shouldn't list the items in suit storage at all (and possibly the ability to retrieve anything should be locked behind access, probably command-level).

#### Steps to reproduce 

1. Have someone enter a cryo tube to leave the round while wearing any piece of clothing that fits in the suit slot (jackets, vests, armour, voidsuits, etc.) while also having an item in the suit storage slot (gun, oxygen tank, probably pouches).
2. Wait for the person in cryo to be removed from the round with the associated radio announcement.
3. Stand in front of the cryogenic oversight console, and either select to dispense all stored items, or pick something that's not stored in the suit slot from the list to dispense just one item.
4. Listen to the machine lie to your face about happily disgorging something that never appears.

#### Length of time in which bug has been known to occur

Since I started playing on Syzygy, I think? Unsure.

#### Client version, Server revision & Game ID

Server revision: master - 2021-03-02
747f4ae0f4a5c660202973155f009fcff77b3628

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
Unable to reproduce.
