### ISSUE TITLE
PACMAN generators don't have defined fuel

### ISSUE THREAD

**Issue by Ikmachek** [Occulus-Server/Occulus-Eris#319]
#### Description of issue
https://i.gyazo.com/38c6c83d93fb09df18e21ded38500f6e.png The picture says it all, the phoron amount is an undefined var. Making the generator not work

#### Difference between expected and actual behavior
A working generator

#### Steps to reproduce 
Wrench down a genny, give it fuel, try to turn it on.

**Comment by Shadow-Quill** [comment]
Well, it seem that the amount of things actually (should™) had no impact on the generator itself, other than what it showed on the interface.

The reason for this, is because there was a missing s in the NanoUI template. That's it.
