### ISSUE TITLE
FBP vital organs are not robotic

### ISSUE THREAD

**Issue by zackerycodestoo** [Occulus-Server/Occulus-Eris#321]
#### Description of issue

While doing some indirectly-related code work, I discovered that FBPs are not actually getting robotic organs! The `nature` variable of their heart/lungs/kidney/liver/stomach is `MODIFICATION_ORGANIC` rather than `MODIFICATION_SILICON`. The code to actually robotize their organs is not triggering.

The fact that the suit sensors program reports them as synthetic is a coincidence -- it's actually failing checks detect the nature of their heart, and the `else` failure state is 'oh, it must be synthetic!' wacky

This is issue is mostly a reminder for myself to investigate the infinity of spaghetti that is organ generation code.

#### Difference between expected and actual behavior

Currently, there are no common issues (exceptional circumstances aside, like transplanting a synthetic crewmember's organs) as a result of using organic organs over silicon organs. I blame this on Eris code not having much effort put into synthetics.

#### Steps to reproduce 

With a prosthetic upper/lower body, view the variables of your heart, lungs, liver, kidneys, or stomach. Their `nature` variable is 0, which bitflags indicate is `MODIFICATION_ORGANIC`. It should be 2, for `MODIFICATION_SILICON`!

#### Specific information for locating

The rabbit hole begins at the `rebuild_organs` proc in `code/modules/mob/living/carbon/human/human.dm:1174`

#### Length of time in which bug has been known to occur

Probably as long as prosthetics have existed on Eris code

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
:spaghetti:

**Comment by Jamini** [comment]
This may have gotten fixed in an upstream port. I'll double check eventually.

**Comment by Michiyamenotehifunana** [comment]
For reference, this is fixed because now all your internal organs can be explicitly turned robotic.
