### ISSUE TITLE
Autodoc autocharges for scan after processes

### ISSUE THREAD

**Issue by Zenitheevee** [Occulus-Server/Occulus-Eris#351]
#### Description of issue

The Autodoc, After doing any process, Will proceed to automatically draw 200 credits for another scan.

#### Difference between expected and actual behavior

Expected behavior: Autodoc does processes and immediately stops

Actual behavior: Autodoc does processes and immediately charges 200 for another scan

#### Steps to reproduce 

Step 1: Use autodoc
Step 2: Experience extraneous healthcare costs

#### Specific information for locating

If i had to guess, Probably autodoc code and maybe processing code?

#### Length of time in which bug has been known to occur

If i had to guess, Ever since the autodoc was installed

#### Client version, Server revision & Game ID

Sunday Highpop 21 March, We dont really have visible round ID's for this.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Michiyamenotehifunana** [comment]
https://github.com/Occulus-Server/Occulus-Eris/blob/913ae0d1900058ff7014b03a1dadf0c52992ba33/code/modules/surgery/autodoc.dm#L200

It seems to be doing it intentionally. 

We could either make it not charge for scans at all, or just comment out that single line.
