### ISSUE TITLE
Fiber collecting provides the users fibers on an object.

### ISSUE THREAD

**Issue by RadiantFlash7** [Occulus-Server/Occulus-Eris#355]
#### Description of issue
When you collect fibers from an object, It'll pull your own fibers as well. Even if it's the first time you've touched it.

#### Difference between expected and actual behavior
I'd expect it to add your fibers after the collection, instead of constantly giving you hits on fibers, only to find out it's yours, despite only touching the object with the collection kit.

#### Steps to reproduce 

use fiber collection on door.
Get excited over getting a hit.
Find out it's your own fibers despite never touching it before???

#### Client version, Server revision & Game ID

Server revision: master - 2021-03-23
72aaac8b252ed850292575611beed372c9b6eeb2

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Shadow-Quill** [comment]
Do note, you can reduce the chance of leaving fibers/fingerprints behind if you're wearing latex gloves (25% to leave something)
