### ISSUE TITLE
Volume based text scaling doesn't respect chat font size.

### ISSUE THREAD

**Issue by gozulio** [Occulus-Server/Occulus-Eris#364]
#### Description of issue
If you increase the font size of the chat window, some messages or parts of messages don't change size accordingly. Player names in Say's will scale correctly, as well as quotation marks, but the actual content of those say's won't scale. Some player action narrations have the same problem. Say's using "1" are unaffected.

#### Example
In this image the font size has been increased to size 24. 
Player names in say's scale appropriately but any dialogue contained within those says doesn't scale at all.

![image](https://user-images.githubusercontent.com/10771387/113275767-230d3e00-92ad-11eb-9603-0c3b1fe3c4ca.png)

#### Client version, Server revision & Game ID
Server revision: master - 2021-03-28
e59bcdc95075ba0613e7a5cecb5c433b17f5cba0
Game ID: 
cbm-aT0K

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by gozulio** [comment]
Basic testing of the issue points towards it being related to the code that scales speech to relative volume.

The way it appears in dream text like this would imply that the module isn't interfacing with chat how it should. As dream text shouldn't have xml formatting in it.
![image](https://user-images.githubusercontent.com/10771387/113278655-2fdf6100-92b0-11eb-82e2-c3e6cb10fb40.png)

From /code/modules/mob/living/say.dm
It seems like the proc hear_sleep() is somehow getting passed XML formatting despite not being in any way prepared to filter or  handle xml formatting.
https://github.com/Occulus-Server/Occulus-Eris/blob/756623c6f5f9afb19afbf82e653470f94ba917cf/code/modules/mob/living/say.dm#L417-L433

**Comment by gozulio** [comment]
Ok, the font size is set here. I don't fully understand how it works but it seems like "2" is the minimum, and it doesn't take into account the actual font size of the chat window, just byonds default font size.
I've found through testing on my own that modifying the value "2" in this code block to something bigger like "10" will indeed make the text larger. Not exactly sure how to fix it to scale off the font size in the clients chat, but at least it's a start.

https://github.com/Occulus-Server/Occulus-Eris/blob/756623c6f5f9afb19afbf82e653470f94ba917cf/code/modules/mob/living/say.dm#L120-L125

CE_SPEECH_VOLUME is defined here. There seems to be some stims that effect your relative volume, which would explain why chemistry is relevant.
https://github.com/Occulus-Server/Occulus-Eris/blob/304af6f10e7838a906e17980f674fc2159349140/code/__DEFINES/chemistry.dm#L55

As for the weirdness with xml formatting appearing in dream text. the formatting is applied to the "message" var in mob/proc/hear_say()
https://github.com/Occulus-Server/Occulus-Eris/blob/cbed9665631e1a6a5a2bcbaaea2487e868ed0055/code/modules/mob/hear_say.dm#L12-L13

This gets inherited by mob/living/proc/hear_say(). When your living mob is asleep, it just yeets the var "message" into mob/living/proc/hear_sleep(). hear_sleep() then tries to split the message into pieces. This includes the formatting in var "message". That's why you'll sometimes see partial bits of xml in dream text.
https://github.com/Occulus-Server/Occulus-Eris/blob/cbed9665631e1a6a5a2bcbaaea2487e868ed0055/code/modules/mob/living/say.dm#L417

NOTE: It feels like the code relating to this would work better with the older CTRL+MOUSEWHEEL method of embiggening the font, and not the current method of physical font size and line height controls.

**Comment by vulppine** [comment]
it looks like that you *could* fix the first problem using inline CSS selectors instead of the old HTML inline definition, i.e.:

rather than, in hear_say(): 

    <FONT size='[speech_volume]`>[message]</FONT>

you could do something like
    
    <span style="font-size:[speech_volume]rem">[message]</span>

however, since BYOND still uses IE for its HTML rendering, this is subject to whatever version of IE you have, and if it can use the `rem` unit: https://caniuse.com/rem

you would have to change the else clause in getSpeechVolume()'s `var/volume` if statement to 1, so that it scales properly with the client's choice of font size by making the message size `1rem`

side effect: if the drug that makes your speech volume super loud ramps it up to like 10, get ready for chat to just **fill** your screen

i'm not 100% sure if this would work, but it can't hurt to try

**Comment by gozulio** [comment]
by changing the else clause in `var/volume` you mean the number 2 at the end of this right?
`var/volume = chem_effects[CE_SPEECH_VOLUME] ? round(chem_effects[CE_SPEECH_VOLUME]) : 2`

The code changes seem to work.
![image](https://user-images.githubusercontent.com/10771387/113412105-6f2bb180-9385-11eb-8bb9-c2e5292b3fa9.png)

We'd have to do the same to the same edits to the sources for pain messages and item interactions and god knows what else.

as for compatibility for `rem`, it looks like it just gets ignored on EI 9, and 10. IE 9's minimum system requirements are windows vista and 7.
Issues might arise with windows XP users using IE8.

**Comment by vulppine** [comment]
yeah, that's what i meant for the else cause

rem compatibility only really applies to people who are running really old versions of IE - which could possibly be the edge case of linux users running SS13 on wine

perhaps just the regular `em` unit would work in this case

as for fixing the other messages that use `<font>`, i guess that's just the way it is - unless somebody can find a quicker solution, this seems to be a solution that works for what it needs to do

**Comment by gozulio** [comment]
With this information I can confidently say that with enough time I can implement the fix. This will effect a lot of files though.

What's worse, is that updating the tags to use `"<span style='font-size:1em'> </span>"` won't match modern convention for formatting text because you're supposed to use predefined classes to format text for consistency. Like so: `"<span class='notice'> </span>"`These usually take core of italicizing, bolding, font resizing and scaling, etc.

I guess my point is i can do it but it won't be pretty.

**Comment by vulppine** [comment]
oh yeah, the inline style is more of a quick fix over anything,

if you really want to add separate classes for message scaling, perhaps it would be best to look at the goonchat stylesheets and modify the messages to instead use those new classes:

https://github.com/Occulus-Server/Occulus-Eris/tree/cbed9665631e1a6a5a2bcbaaea2487e868ed0055/code/modules/goonchat/browserassets/css
