### ISSUE TITLE
Meson Scanners do not allow viewing ore veins as intended

### ISSUE THREAD

**Issue by Jamini** [Occulus-Server/Occulus-Eris#37]
#### Description of issue

Meson scanners are not able to see ore through rock walls

#### Difference between expected and actual behavior

Original intention of Meson scanners was to see ore deposits through walls.
Eris changed this at some point.
We need this fixed/reverted to intended behavior.

#### Steps to reproduce 

1. Equip meson scanners
2. Go to the asteroid
3. Activate mesons
4. See deposits through walls.

#### Specific information for locating

This is likely caused because ores are now an overlay rather than a type of wall. We may need to implement some spaghetti code or modify mesons so they can see overlays. Whichever is cleaner.

#### Length of time in which bug has been known to occur

Uncertain, but likely since ore was reworked years ago

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
Digging into this on a hint from RadiantFlash, it seems that archaeology spots can still be seen properly using mesons (the rocks with them use a variable called _archaeo_overlay_), but I haven't been able to determine from VV alone how the ores show their overlays. I'll dig into the code and have a look
