### ISSUE TITLE
Throwing a dirty, modified gun in Engineering's reconstitutor prints a clean gun with the stats of the mods, but without the mods.

### ISSUE THREAD

**Issue by DARG0N** [Occulus-Server/Occulus-Eris#424]
#### Description of issue

Putting a modified, dirty gun in Engineering's reconstitutor eats the gun's mods, but does not remove the effect of those mods. In this particular case, a Gladstone with an Overshooter and Danger Zone Trigger is unable to have its safety turned on, and has a base ammo capacity of 13, including the chambered round. This leaves space to add new mods to the same gun, apparently without losing the effects of the mods that were eaten by the reconstitution process.

#### Difference between expected and actual behavior
One would expect the mods to either disappear entirely or be put on the reconstituted weapon, but no - that doesn't happen. Mod effects persist while the mod slots are freed.

#### Steps to reproduce 
 
-Find dirty gun
-Modify dirty gun
-Put dirty gun in Engineering's reconstitutor.
-Put more mods on the gun.
-The TactiCool Incident, 4/27/2421

#### Specific information for locating

At the fear of sounding redundant;
The specific weapon used when I discovered this was a Gladstone. The mods on it were a Danger Zone Trigger, an Overshooter, and possibly a grip? I don't remember if there was grip.
Engineering's Equipment Reconstitutor thing, in the same room as The Cube.

#### Length of time in which bug has been known to occur

Just discovered this. I reckon it's probably happened before in the past, but I've not heard anyone talk about it.

#### Client version, Server revision & Game ID

Server revision: master - 2021-04-26
c5553b6c96aa3f92cd5a834ce149c2516e07761f

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
This is a function of how make_young works. a totally new device is spawned and the old one is destroyed.

**Comment by Jamini** [comment]
This is a bug, but it is becoming a feature.
