### ISSUE TITLE
Aegis Survival Soul Crypt program doesn't function as intended

### ISSUE THREAD

**Issue by RadiantFlash7** [Occulus-Server/Occulus-Eris#475]
#### Description of issue
The soulcrypt program actually adds nutrition to you, rather then removing it during use. Meaning it can be used infinitely.

#### Difference between expected and actual behavior
Theoretically, it should drain nutrition while active, since it gives a stats buff. Instead it gives both a stat buff and adds nutrition.

#### Steps to reproduce 
Have half nutrition, 
Activate survival crypt program
Watch as it fills to green over time.

#### Specific information for locating

Probably just needs values adjusted in the crypt program code.

#### Length of time in which bug has been known to occur

Couple days. Mentioned it to Tori a bit back, but we probably should have an issue posted so it doesn't get forgotten.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by SigDoesCode** [comment]
This isn't just the aegis survival, it's all soulcrypt programs I've tested so far. I think it's tied to the fact that the drain is 5 instead of -5? Or maybe there's an issue in the drain proc?

**Comment by Michiyamenotehifunana** [comment]
This is due to the fact that the adjustnutrition() proc adds onto a mob's nutrition rather than subtracting from it, which is clearly not what the original coder of the soulcrypts thought it did. This means that this bug has been present since soulcrypts were first created, however it wasn't readily apparent as there was essentially no usable soulcrypt modules nor was the energy processing proc actually functional, up until recently. Should be an easy fix.

**Comment by SigDoesCode** [comment]
Holy shit, this is that old? Fantastic. Well in that case that should be an easy fix, just gotta find adjustnutrition() then. I can't get around to it this weekend but most likely on monday.

**Comment by Jamini** [comment]
Shouldn't even need to find adjustnutrution(), just negate the value in there (So whatever value is in the adjustnutrution call, make it a negative)

**Comment by Michiyamenotehifunana** [comment]
Fixed in #561.
