### ISSUE TITLE
HUDs are spawning as items

### ISSUE THREAD

**Issue by ShadzFen** [Occulus-Server/Occulus-Eris#500]
#### Description of issue
Some kind of HUD is spawning as items in stash as loot and in the world loot spawns too. Looks like it's the HUD for some kind of glasses.

![image](https://user-images.githubusercontent.com/45645502/120534087-bb28c000-c3e1-11eb-8af2-e0168f8ee1ae.png)

#### Difference between expected and actual behavior
This shouldn't be spawning at all! This is an element that is part of an object, but is spawning as its own object for whatever reason.

#### Steps to reproduce 
Just searching loot or right clicking the environment and getting lucky enough to find one. As seen in the picture, the sprite is invisible.

#### Specific information for locating

The picture shows variables that can help in finding the code.

#### Length of time in which bug has been known to occur

No idea when this started, I only just got back from a very long break.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
This is not quite accurate. This is the object that replaces HUDs when they break from the make_old proc. It doesn't have a sprite because it's supposed to inherit the sprite from the parent hud.

Toss a spawn_blacklisted = true tag on it and it should stop spawning.
