### ISSUE TITLE
Global FPS preference does not persist between rounds.

### ISSUE THREAD

**Issue by razekpraxis** [Occulus-Server/Occulus-Eris#549]
#### Description of issue
Currently, the recently added client FPS setting needs to be reapplied every time a new round begins, otherwise the client will default to server-side FPS. The number in the setting will remain, though it will not be applied.

#### Difference between expected and actual behavior
The setting should be consistent between rounds and restarts, however it is not.

#### Steps to reproduce 
Change FPS in Global settings.
Wait for round restart. 

#### Specific information for locating
The setting is located in Character Setup, under the Global tab. 

#### Length of time in which bug has been known to occur
Bug has been present since June 7th when FPS was re-enabled.

#### Client version, Server revision & Game ID
Server revision: master - 2021-06-13
a345942bc37552a476a3af1464ec0a3418ada9e5

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Michiyamenotehifunana** [comment]
An oversight on my part. Should be easy to fix by hooking onto the thingies that run when a user logs in.

**Comment by Michiyamenotehifunana** [comment]
As seen here on Polaris: https://github.com/PolarisSS13/Polaris/blob/26f17d2780841b98de25e3666f136199d66c837d/code/modules/mob/login.dm#L38
