### ISSUE TITLE
Design disks displaying the wrong sprite when held in hand.

### ISSUE THREAD

**Issue by ShadzFen** [Occulus-Server/Occulus-Eris#560]
#### Description of issue
Some design disks are displaying the ironhammer sledgehammer sprite when held in hand. I'm unsure if it's only the security related disks, or all of the disks. 
The fix for it should be as simple as changing the icon when held in hand, so it's a good first issue for people who want to start learning DM.

![image](https://user-images.githubusercontent.com/45645502/122570732-52318100-d04c-11eb-9534-035584649292.png)

#### Difference between expected and actual behavior
They shouldn't be displaying this sprite at all! I'm unsure what sprite they should be displaying instead, but I'm pretty sure it's not a sledgehammer.

#### Steps to reproduce 
Hold a design disk.

#### Specific information for locating

https://github.com/Occulus-Server/Occulus-Eris/blob/e54e7b24b99dcb8c580cfd78dcd93c37ff4ea369/code/game/objects/items/weapons/design_disks/ironhammer.dm

#### Length of time in which bug has been known to occur

No clue. A few weeks now I guess

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
This was an intended meme over on Eris side. Pretty sure.

**Comment by Michiyamenotehifunana** [comment]
There's an upstream PR that fixes a bunch of fucked up inhands.

**Comment by RadiantFlash7** [comment]
I’m pretty sure this is actually all disk inhands, though the other ones use different hammers then the iron hammer iirc
