### ISSUE TITLE
Cameras are spawning in junk fields

### ISSUE THREAD

**Issue by Jamini** [Occulus-Server/Occulus-Eris#566]
#### Description of issue
Cameras on the JTB fields are linked to the Northern Light network randomly

#### Difference between expected and actual behavior
Junk fields probably shouldn't have cameras

#### Steps to reproduce 
1. Generate junk field
2. Check camera console

#### Length of time in which bug has been known to occur

As long as we have had JTB ported

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by SigDoesCode** [comment]
Hey Shadz is this an irrelevant issue now because we removed the JTB area?

**Comment by Michiyamenotehifunana** [comment]
Junk fields no longer exist, reopen if we ever port them back.
