### ISSUE TITLE
Female women cannot select beards

### ISSUE THREAD

**Issue by IrkallaEpsilon** [Occulus-Server/Occulus-Eris#594]
#### Description of issue

In character creator women cannot select beards. This more importantly locks out female Unathi from picking spinal spikes and dorsal frilss, both commonly found on lizards no matter the gender. Unathi are based on Lizards.

#### Difference between expected and actual behavior

Being able to pick beards a woman like IRL could in theory.

#### Steps to reproduce 

Go into character creator, pick gender female, then try assign a beard.

#### Specific information for locating
 
n/A

#### Length of time in which bug has been known to occur

It is in character creator.

#### Client version, Server revision & Game ID

Current version. Ongoing issue.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by razekpraxis** [comment]
Resolved with #645 
Additional facial options are available in the ears slot in character customisation
