### ISSUE TITLE
The Lootbag's noth facing in-hand sprite is inverted. 

### ISSUE THREAD

**Issue by ShadzFen** [Occulus-Server/Occulus-Eris#603]
#### Description of issue

When holding a Lootbag variant of the duffle bag and facing north, the sprite will be in the opposite hand. So if holding it in the left hand, it will show the sprite to hold it in the right hand, and vice versa.
![image](https://user-images.githubusercontent.com/45645502/126018174-d9c83547-f7da-44ba-990c-4316920e2c16.png) ![image](https://user-images.githubusercontent.com/45645502/126018192-f1f4055a-db01-4283-91ef-817945ff3edc.png)

I checked all other directions and they are working as intended. It's only when facing north.

#### Difference between expected and actual behavior

These should be inverted.

#### Steps to reproduce 

Hold a lootbag duffle bag and look north.

#### Specific information for locating

![image](https://user-images.githubusercontent.com/45645502/126018257-77941e70-091e-405a-84c0-09257ba21dd2.png)

#### Length of time in which bug has been known to occur

Probably since it was added.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Jamini** [comment]
This appears to be an issue with the upstream files. I'm fixing it, but we'll need to be alert for upstream fixing it.
