### ISSUE TITLE
Tearing off floor tiles repeatedly before the action is done will carry through every layer until a player falls down a Z-Level

### ISSUE THREAD

**Issue by Sydrec** [Occulus-Server/Occulus-Eris#608]
#### Description of issue

> Sydrec: Holy shit two tiles south and you would've been in SPACE.
> Ryoken: JEEZ

An amusing little bug that's more than likely caused by multiple, stacked actions finishing off and applying themselves to a grid space's topmost floor-layer. What could start as a small check of Robustness to remove a floor tile and easily punch through the thickest of ship hulls.

#### Difference between expected and actual behavior

Expected: Player ripping up a floor tile to be able to use as a weapon or place back down.

Actual: A player ripping up a floor tile and continuing to dig a hole, resulting in banishment to the lower decks (or space depending on Z-Level and location.)

#### Steps to reproduce 
Shift click tile, click "Apply robustness"

![OCCULUS-RyokuFloorgrab](https://user-images.githubusercontent.com/4873207/126417609-d229f948-0c05-4585-8e39-0dfb75783389.PNG)
![OCCULUS-QuinnFloorgrab](https://user-images.githubusercontent.com/4873207/126417608-71c9aaad-5ea1-43af-ac13-7788df467bae.png)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by SigDoesCode** [comment]
I'm trying to work on this but the way that SS13 handles floors is infuriating. 
Currently attempting: add a flag to plating and its children to make it not rippable, then check for the flag on rip. 
What happens: Floor tiles inherit this too. Why.
