### ISSUE TITLE
trade beacon circuitboard causes runtime when trying to build it

### ISSUE THREAD

**Issue by Greenjoe12345** [Occulus-Server/Occulus-Eris#627]
#### Description of issue
when trying to build a trade beacon, with it's curcuitboard and one ansible crystal, it will runtime when trying to finish it with a screwdriver, as it is trying to make an object of type null
the circuit board also lacked a name other then just circuit board.
![image](https://user-images.githubusercontent.com/33647525/128286194-e143a48f-292c-4a4d-b424-f6033ff941fd.png)

#### Difference between expected and actual behavior
it should make a trade beacon, but instead it runtimes.

#### Steps to reproduce 
get a trade beacon circuitboard, try to build the machine, runtime.

#### Specific information for locating
/obj/item/weapon/electronics/circuitboard/trade_beacon

#### Client version, Server revision & Game ID
Server revision: master - 2021-08-03
ba47b2390033718d3bb4062ffa62d684395fad80

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by razekpraxis** [comment]
it should be noted that i don't believe that the base trade beacon was ever intended to be built in the first place, but ive implemented a change to stop it runtiming
