### ISSUE TITLE
Potential Disposals/mail exit point errors.

### ISSUE THREAD

**Issue by Acryonic** [Occulus-Server/Occulus-Eris#680]
#### Description of issue
Appearing in a unexpected spot when sending a maintenance drone with the mail tag "Cargo bay".

#### Difference between expected and actual behavior
Expected to end up in the cargo bay office, ontop of the disposal unit itself.
instead end on the table next to the cash registry, and having spawned a "Broken tile" object on the spot you emerge.

#### Steps to reproduce 
Spawn as Maintenance drone, Walk to nearest useable disposals unit, Mail tag yourself to the Cargo office before proceeding to take a Disposals Joyride, Pop up on the table alongside your new broken tile object.

#### Specific information for locating

In the blue square is the unexpected Exit location.
![Cargoofficemailerror](https://user-images.githubusercontent.com/64962881/131197876-43ce3421-a57d-4c81-8ca9-bce15d1649ce.PNG)

#### Length of time in which bug has been known to occur

Assuming at the earliest After the latest cargo remap.

#### Client version, Server revision & Game ID

Client version: 513.1542
Server revision: master - 2021-08-26
6c2028b2ab882e41f3a41288f41fcd3c8b88f51c

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by SigDoesCode** [comment]
This is a disposals issue, it looks like the pipe from the chute in the office isn't finished.

**Comment by Acryonic** [comment]
Yes, looks like it, I did a second check, but there is disposal pipes all the way to the actual Bin, so im wondering if theres certain disposal pipes that are Trash only, and then some that are multi-purpose?

**Comment by Shadow-Quill** [comment]
There is not, actually. There's a missing pipe under the door.
And no, there's only one type of disposal pipe.
