### ISSUE TITLE
Meteors can impact and damage the ship before the round has started

### ISSUE THREAD

**Issue by cebutris** [Occulus-Server/Occulus-Eris#69]
#### Description of issue
During the lobby, meteors can still impact and damage the ship, even though the round has not started. 

#### Difference between expected and actual behavior
Before the round begins, nothing should happen.

![image](https://user-images.githubusercontent.com/26630607/101638633-4c534700-39fc-11eb-9809-1ed1f84dc50d.png)

The captain's bedroom, breached before the round started.
![image](https://user-images.githubusercontent.com/26630607/101640162-27f86a00-39fe-11eb-9686-4c044e055f9f.png)

**Comment by cebutris** [comment]
#69, nice

**Comment by ShadzFen** [comment]
I was gonna say that's kindof a cool bug, cus it means there's a chance the ship will start slightly broken. But the fact that it can be as unlucky as to break open the captain's quarters and vent out everything is a bit meh

**Comment by Jamini** [comment]
This is due to overmap initializing before the round starts. We can just move overmap starting to after the round begins. It's not that intensive anyway.
