### ISSUE TITLE
Blank message in the chat box

### ISSUE THREAD

**Issue by Leon9621** [Occulus-Server/Occulus-Eris#695]
#### Description of issue
After taking a drink of straight vodka, an empty message would appear in the chat. It didn't seem to be a previous message having a line break - the chat moved up by itself a full second after the drink, and it seemed to repeat with each drink.

#### Difference between expected and actual behavior
If there is something happening because I took a drink of vodka, there should be text to say what happens. If nothing happens, then there shouldn't be a message.

#### Steps to reproduce 
1. Acquire bottle of vodka
2. Drink from bottle of vodka
3. ????
4. Blank message

#### Specific information for locating

https://i.imgur.com/NSZTlGN.png You can see it after "Ie Samase coughs!" It's repeated three times. (The coughs were manual because straight vodka is rough)

#### Length of time in which bug has been known to occur

I noticed it yesterday but kind of wrote it off as a one off thing.

#### Client version, Server revision & Game ID

60d491111f74f41b2c06f65c8eec30b8800ad194

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Leon9621** [comment]
Little thing to append here; I got the message after drinking from a bottle of tequila as well. Might also be relevant that I was playing as an engineer at the time, with that perk for a temporary COG buff when you're drunk.

**Comment by Ikmachek** [comment]
This is something I notice playing a churchie and being around Obelisks so I hard suspect this is tied to sanity gain somehow.

**Comment by Jamini** [comment]
Fixed in #762
