### ISSUE TITLE
Using mirrors links you to them

### ISSUE THREAD

**Issue by ScalesyScales** [Occulus-Server/Occulus-Eris#697]
#### Description of issue
If you use a mirror, your body becomes eternally linked to them. If that mirror is deleted, so will your body be deleted.
https://i.gyazo.com/662858cf9690d86eecee3569346136bc.png
https://i.gyazo.com/8a8da1f99c506ad6be05c53f43ecb166.png
#### Difference between expected and actual behavior
Deleting a mirror shouldn't delete the bodies connected to them

#### Steps to reproduce 
Spawn a mirror, use it to change your hair. Delete the mirror. You are now deleted.

#### Specific information for locating

/ obj/structure/mirror

#### Length of time in which bug has been known to occur

No clue

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by SigDoesCode** [comment]
This is definitely related to the way that the mirror tracks the person using it, but I'm not sure how. Testing has just made me delete myself over and over again.
