### ISSUE TITLE
Soulcrypt access updater breaks ID access after first update

### ISSUE THREAD

**Issue by Zenitheevee** [Occulus-Server/Occulus-Eris#743]
#### Description of issue

After updating soulcrypt access once, Using the access update deletes access on both the soulcrypt and the ID.

#### Difference between expected and actual behavior

Expected behavior: I honestly dont know what to expect, maybe removing access from the crypt.. but definitely not what actual behavior is

#### Steps to reproduce 

Step 1: Have Soulcrypt(Start or implanted, does not matter)
Step 2: Get the Soulcrypt Access Updater from medical
Step 3: Stick card into it
Step 4: Use it
Step 5: Use it again
Step 6: Watch as you now have less access than a vagabond. All your access, Gone. Reduced to Atoms. 

#### Specific information for locating

man fuck if i know, to be honest. Maybe the /access_update_tool/ code? Maybe ID card code? I have no genuine idea.

#### Length of time in which bug has been known to occur

I honestly have no idea when it started. For all i know its a sneaker problem thats never been solved or noticed because who updates their soulcrypt access twice?

#### Client version, Server revision & Game ID

Server revision: master - 2021-10-23
[2e0c685e3f415874fc844e0463197980541e8d07](https://github.com/Occulus-Server/Occulus-Eris/commit/2e0c685e3f415874fc844e0463197980541e8d07)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Shadow-Quill** [comment]
fixed in #748
