### ISSUE TITLE
Noble oddities do not work.

### ISSUE THREAD

**Issue by CDRDecky** [Occulus-Server/Occulus-Eris#771]
#### Description of issue

Character-spawned oddities done by the Noble background do not level up any stat at all when used for insight level-up. 

#### Difference between expected and actual behavior

Expected: Stats being leveled up by the oddities as expected, with feedback telling you what leveled up and by how much.
Actual behaviour: The normal text comes up: 'You have rested well and improved your stats' without your stats being leveled up. As if you leveled insight without an oddity in your inventory.

#### Steps to reproduce 
Pick Noble background. Spawn with oddity. Level up.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Acryonic** [comment]
The merchant not being able to use wads of money for the same purpose might be related.

**Comment by Jamini** [comment]
Oh right, I was going to investigate this yesterday. Back into the breach!

**Comment by Shadow-Quill** [comment]
Appears to be fixed by https://github.com/Occulus-Server/Occulus-Eris/pull/780
