### ISSUE TITLE
Unholstering guns on certain items deletes the gun

### ISSUE THREAD

**Issue by Zenitheevee** [Occulus-Server/Occulus-Eris#775]
#### Description of issue

On certain items, Including but not limited to:
>Medium cells
>Other guns

Unholstering a gun will delete the holstered gun, Saying its now in your hand and pointing down, but being neither on the ground or in the other hand

#### Difference between expected and actual behavior

Expected behavior should either being denied your ability to unholster, or for it to be unholstered into a free, empty hand or onto the ground.

Actual behavior is for it to be deleted, through means i'm not sure

#### Steps to reproduce 

Step 1: Get a holster on your uniform and a pistol in the holster
Step 2: Get something in your hand. Test around what items, For me i noticed i deleted a Gemini into a Clarissa
Step 3: Unholster the gun
Step 4: Forget to ahelp, instead just L/OOC that you deleted something

#### Specific information for locating

I'd probably link it to holster code

#### Length of time in which bug has been known to occur

Seems atleast a week... Maybe two?

#### Client version, Server revision & Game ID

2021-12-05
2cc7e58c0eead8cdba7c5fe221a1072b2593a696
Though, i remember it having been there for a while

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Shadow-Quill** [comment]
reportedly fixed by https://github.com/Occulus-Server/Occulus-Eris/pull/777
