### ISSUE TITLE
Antag SBR Uplink Invisible

### ISSUE THREAD

**Issue by Hawk-v3** [Occulus-Server/Occulus-Eris#781]
#### Description of issue

Antag Station Bounced Radio Uplink has no icon.

#### Difference between expected and actual behavior

To see the icon when I have it.

#### Steps to reproduce 

Be Antag, get SBR Uplink.

#### Client version, Server revision & Game ID

Happened 11/12/2021

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by SigDoesCode** [comment]
Simple fix.
