### ISSUE TITLE
Missing/Broken Sprite List -- Feb 17, 2022

### ISSUE THREAD

**Issue by SigDoesCode** [Occulus-Server/Occulus-Eris#832]
#### Description of issue
A few of the new updates broke a bunch of sprites. This is an ongoing issue to keep track of any sprites that people note are missing and see how they can be fixed.

#### Difference between expected and actual behavior
Sprites are missing that shouldn't be. 

#### Specific information for locating

Currently I know of: 
-- The new drink sprites that Shadz added a while back (milkshakes, etc.)
-- Bicardine syringes don't have a syringe in their sprite, only using the liquid inside overlay.

#### Client version, Server revision & Game ID

master - 2022-02-10
[5bdf892b8fc758f031d73c3827e29da61263a944](https://github.com/Occulus-Server/Occulus-Eris/commit/5bdf892b8fc758f031d73c3827e29da61263a944)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Occulus-Server/Occulus-Eris/issues)

**Comment by ShadzFen** [comment]
The issues listed are no longer relevant and or have been fixed.
