### ISSUE TITLE
Drones cannot click things on screen.

### ISSUE THREAD

**Issue by subtumaka** [Occulus-Server/Occulus-Eris#85]
#### Description of issue
Can't click anything on screen as a drone, this include electronics such as consoles or apcs to open their windows. As well as the tools in your inventory to equip them to the hotbar. 

#### Difference between expected and actual behavior
Can't click electronics to open their window, can't click on tools in inventory to equip them. 

#### Steps to reproduce 
Join as drone, try to do take shovel from INV onto hotbar, cry at being unable to click on anything.

#### Specific information for locating
Not sure, at least I think it's a bug as it happened before a restart and after. I have not played in a while so I am unsure
of when it started precisely. According to Sydrec whom I asked also to test out drone:
Okay, I can:
-Activate tools using the Panel button
-CANNOT interact with activated tools (ig, ignite Drone Welder)
-CAN  use "Activate Held Object" verb to interact with activated tools (ig, ignite drone welder)
-CAN use shortcuts to manipulate doors
-CANNOT Click to access menus
-CANNOT Click to Interact

#### Length of time in which bug has been known to occur
Sometime between possibly Dec 13 to today Dec 17

#### Client version, Server revision & Game ID
BYOND VER: 513.1528
Server revision: master - 2020-12-17
5f1f7b102049506bc53b8956f60159f474a8eb7c

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Michiyamenotehifunana** [comment]
Should have been fixed by #86. Please confirm.

**Comment by ShadzFen** [comment]
Apparently this got fixed! I dunno what PR fixed it, but it probably should have been linked. Angery!!!!!111!
Issue closed!
