### ISSUE TITLE
AI's cannot view peoples flavor texts

### ISSUE THREAD

**Issue by SoulZeDurg** [Occulus-Server/Occulus-Eris#901]
#### Description of issue

AI's cannot view peoples flavor texts after examining them, clicking 'more' to see it all does nothing.

#### Difference between expected and actual behavior

You should be able to view their flavor texts.
You cannot.

#### Steps to reproduce 

Step 1: Be an AI
Step 2: Look at someone with your cams
Step 3: Examine them
Step 4: Click 'more' to see their flavor text.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Occulus-Server/Occulus-Eris/issues)

**Comment by SigDoesCode** [comment]
Ten bucks says this is because the "more" doesn't check for where the camera is but where the mob is. I know I can't do it while I'm outside view range of the person.
